### PR TITLE
Feature bug fix

### PR DESCRIPTION
**Pull request by nimit2801**
## Description

The project won't work on the node versions above 15.xx, because there's a dependency node-sass that needs 14.xx and lower.
image

## Motivation and Context

- This change was required because the project won't run on the current version of the node (15.xx and above)

#20
 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by nimit2801** [comment]
https://www.npmjs.com/package/node-sass @sansyrox

**Comment by nimit2801** [comment]
**I'm happy to this is my second PR too.** 
Also @sansyrox I couldn't make new PR this commit was automatically included in the existing PR.

This also solved another issue #16 with commit https://github.com/mexili/cssify/pull/21/commits/c5d75bf03b28eef9180c6864863e438ee0519d7a as suggested @sansyrox I've disabled minify temporarily and allowed to only css files from the browser. 
This would allow normal working of the css framework and help the project run smoothly.

_I've made one small change in package.json made_ 
"server" : "nodemon server.js" => "server" : "node server.js"
Reason: As new files were generated in on the backend in the temp folder the server was restarting detecting the temp files added which made the server restart, which can cause delay and loss API calls on the server.

**I'll soon open one PR to minify the CSS versions. Thank You.**

**Comment by sansyrox** [comment]
Hi @nimit2801 , can you please remove the package-lock.json from the commits? We don't commit them in the repo.

**Comment by nimit2801** [comment]
> 
> 
> Hi @nimit2801, can you please remove the package-lock.json from the commits? We don't commit them in the repo.

yeah sure, I'll remove it from the commit.

**Comment by nimit2801** [comment]
@sansyrox 
1. Deleted backend/package-lock.json and client/package-lock.json from the main branch. 
2. Added both files to .gitignore. with
732efe8479eaebe8927da270384d56bf47b70a96 and 147740fa05481cd010b6cf05d10a3da67392dcd3

**Comment by sansyrox** [comment]
Hi @nimit2801 ,

Looks good. I would've given you marks of 50 + 50, i.e. two medium issues. But I'll give you 100 in a single one.

**Pull request merged**
